name: "test this action"
on: [pull_request, push]

jobs:
  test-action:
    runs-on: ubuntu-latest
    steps:
    - name: Changelog Reminder
      uses: peterjgrainger/action-changelog-reminder@v1.1.1
